version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=makerdao
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=DocumentDrive
    ports:
      - "5444:5432"
    volumes:
      - db:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
volumes:
  db:
    driver: local
