name: Release

on:
    push:
        branches: [production, main]
    workflow_dispatch:

env:
    HUSKY: 0

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 20.x
            - name: Install dependencies
              uses: pnpm/action-setup@v3
              with:
                  version: latest-8
                  run_install: true
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: pnpm run release
